### ISSUE TITLE
abcpy installation issue

### ISSUE THREAD

**Issue by Konstantius** [eth-cscs/abcpy#97]
I failed to install abcpy package and absolutely have no ideas about the causes.
During installation the 200-lines log file was generated, but I cannot reveal the bugs. 
E.g., there is the "error: Microsoft Visual C++ 14.0 or greater is required", but in fact Visual Studio 2019 Developer v16.11.3 is installed.
I attached the log below. Maybe, it will help to hunt down a question.
Thanks in advance.
[ABCpy.txt](https://github.com/eth-cscs/abcpy/files/7175900/ABCpy.txt)

**Comment by statrita2004** [comment]
Hi, Your issue is due to the failure in installation of the package glmnet, ABCpy uses this package. The original codes of glmnet is written in Fortran and hence you need to have access to Fortran compilers in your machine. Please consult how to install glmnet package for this. Further it looks like you are using Windows OS, we provide support only for Linux or Mc OS. On those two other OS, this is not an issue as these compilers are always there and easily accessible.

**Comment by Konstantius** [comment]
So, ABCpy cannot be used under Windows?

**Comment by LoryPack** [comment]
Hi @Konstantius, thanks for your interest in ABCpy! In principle ABCpy can be used in Windows, if all dependencies are satisfied in the right way. However it is trickier in Windows to get everything working correctly, as you experienced, so that we do not test ABCpy releases on Windows. If you have access to a Linux machine, that would make your life much simpler. 

However, if you manage to install ABCpy succesfully on Windows, we'd love to hear the steps you followed, as they may help other users in the future!

**Comment by Konstantius** [comment]
Thank you, Lorenzo. I'll try to find other ways to deal with bayesian stats besides ABCpy.

**Comment by Gabriel-p** [comment]
As far as I can see the `glmnet` package is only required for the `PenLogReg` classes:

https://github.com/eth-cscs/abcpy/blob/48c47154da5196ba01b868edb8a276e688ba69bf/abcpy/distances.py#L267

https://github.com/eth-cscs/abcpy/blob/d0e6181f737438f13ea7af41dd0ac435f15322b6/abcpy/approx_lhd.py#L386

Couldn't the code be refactored so that this package is only required if either of these classes is used?

**Comment by LoryPack** [comment]
Hi Gabriel. 

I think it is a possibility. We will work on that soon. If `glmnet` still gives you troubles, you can try to install ABCpy from source rather than using `pip`; see the [docs here](https://abcpy.readthedocs.io/en/latest/installation.html). After downloading the source as described there, to avoid having to install `glmnet` you can simply remove it from the `requirements.txt` and from the two files where it is used (simply removing the imports should be enough). Then proceed with the installation as indicated. 

That should allow to use all `ABCpy` functionalities which do not require `glmnet`

**Comment by LoryPack** [comment]
Following my last message and to make things easier, I have created a branch in my fork where I removed glmnet and all code which uses it, as a temporary solution. Then I suggest you install ABCpy via:

 pip install git+https://github.com/LoryPack/abcpy.git@no_glmnet

rather than the usual way. Hopefully that solves the issues you experience.
